# Configuration file for ReadTheDocs
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
  install:
    - requirements: docs/requirements.txt

# Build HTML and PDF documentation
# https://docs.readthedocs.io/en/stable/guides/pdf-non-ascii-languages.html
