# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polarway_pb2 as polarway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polarway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataFrameServiceStub(object):
    """Main DataFrame service - all operations are immutable and return new handles
    ===== File I/O Operations =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadParquet = channel.unary_unary(
                '/polarway.v1.DataFrameService/ReadParquet',
                request_serializer=polarway__pb2.ReadParquetRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.ReadCsv = channel.unary_unary(
                '/polarway.v1.DataFrameService/ReadCsv',
                request_serializer=polarway__pb2.ReadCsvRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.ReadRestApi = channel.unary_unary(
                '/polarway.v1.DataFrameService/ReadRestApi',
                request_serializer=polarway__pb2.RestApiRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.WriteParquet = channel.unary_unary(
                '/polarway.v1.DataFrameService/WriteParquet',
                request_serializer=polarway__pb2.WriteParquetRequest.SerializeToString,
                response_deserializer=polarway__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.WriteCsv = channel.unary_unary(
                '/polarway.v1.DataFrameService/WriteCsv',
                request_serializer=polarway__pb2.WriteCsvRequest.SerializeToString,
                response_deserializer=polarway__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.StreamWebSocket = channel.unary_stream(
                '/polarway.v1.DataFrameService/StreamWebSocket',
                request_serializer=polarway__pb2.WebSocketSourceRequest.SerializeToString,
                response_deserializer=polarway__pb2.ArrowBatch.FromString,
                _registered_method=True)
        self.StreamRestApi = channel.unary_stream(
                '/polarway.v1.DataFrameService/StreamRestApi',
                request_serializer=polarway__pb2.RestApiRequest.SerializeToString,
                response_deserializer=polarway__pb2.ArrowBatch.FromString,
                _registered_method=True)
        self.StreamGrpc = channel.unary_stream(
                '/polarway.v1.DataFrameService/StreamGrpc',
                request_serializer=polarway__pb2.GrpcStreamRequest.SerializeToString,
                response_deserializer=polarway__pb2.ArrowBatch.FromString,
                _registered_method=True)
        self.StreamMessageQueue = channel.unary_stream(
                '/polarway.v1.DataFrameService/StreamMessageQueue',
                request_serializer=polarway__pb2.MessageQueueRequest.SerializeToString,
                response_deserializer=polarway__pb2.ArrowBatch.FromString,
                _registered_method=True)
        self.Filter = channel.unary_unary(
                '/polarway.v1.DataFrameService/Filter',
                request_serializer=polarway__pb2.FilterRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Select = channel.unary_unary(
                '/polarway.v1.DataFrameService/Select',
                request_serializer=polarway__pb2.SelectRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.WithColumn = channel.unary_unary(
                '/polarway.v1.DataFrameService/WithColumn',
                request_serializer=polarway__pb2.WithColumnRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.WithColumns = channel.unary_unary(
                '/polarway.v1.DataFrameService/WithColumns',
                request_serializer=polarway__pb2.WithColumnsRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Drop = channel.unary_unary(
                '/polarway.v1.DataFrameService/Drop',
                request_serializer=polarway__pb2.DropRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/polarway.v1.DataFrameService/Rename',
                request_serializer=polarway__pb2.RenameRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Sort = channel.unary_unary(
                '/polarway.v1.DataFrameService/Sort',
                request_serializer=polarway__pb2.SortRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Unique = channel.unary_unary(
                '/polarway.v1.DataFrameService/Unique',
                request_serializer=polarway__pb2.UniqueRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Limit = channel.unary_unary(
                '/polarway.v1.DataFrameService/Limit',
                request_serializer=polarway__pb2.LimitRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Head = channel.unary_unary(
                '/polarway.v1.DataFrameService/Head',
                request_serializer=polarway__pb2.HeadRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Tail = channel.unary_unary(
                '/polarway.v1.DataFrameService/Tail',
                request_serializer=polarway__pb2.TailRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Slice = channel.unary_unary(
                '/polarway.v1.DataFrameService/Slice',
                request_serializer=polarway__pb2.SliceRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.GroupBy = channel.unary_unary(
                '/polarway.v1.DataFrameService/GroupBy',
                request_serializer=polarway__pb2.GroupByRequest.SerializeToString,
                response_deserializer=polarway__pb2.GroupByHandle.FromString,
                _registered_method=True)
        self.Agg = channel.unary_unary(
                '/polarway.v1.DataFrameService/Agg',
                request_serializer=polarway__pb2.AggRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Pivot = channel.unary_unary(
                '/polarway.v1.DataFrameService/Pivot',
                request_serializer=polarway__pb2.PivotRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Melt = channel.unary_unary(
                '/polarway.v1.DataFrameService/Melt',
                request_serializer=polarway__pb2.MeltRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Join = channel.unary_unary(
                '/polarway.v1.DataFrameService/Join',
                request_serializer=polarway__pb2.JoinRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Cross = channel.unary_unary(
                '/polarway.v1.DataFrameService/Cross',
                request_serializer=polarway__pb2.CrossRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.AsTimeSeries = channel.unary_unary(
                '/polarway.v1.DataFrameService/AsTimeSeries',
                request_serializer=polarway__pb2.AsTimeSeriesRequest.SerializeToString,
                response_deserializer=polarway__pb2.TimeSeriesHandle.FromString,
                _registered_method=True)
        self.Resample = channel.unary_unary(
                '/polarway.v1.DataFrameService/Resample',
                request_serializer=polarway__pb2.ResampleRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.RollingWindow = channel.unary_unary(
                '/polarway.v1.DataFrameService/RollingWindow',
                request_serializer=polarway__pb2.RollingWindowRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Lag = channel.unary_unary(
                '/polarway.v1.DataFrameService/Lag',
                request_serializer=polarway__pb2.LagRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Lead = channel.unary_unary(
                '/polarway.v1.DataFrameService/Lead',
                request_serializer=polarway__pb2.LeadRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Diff = channel.unary_unary(
                '/polarway.v1.DataFrameService/Diff',
                request_serializer=polarway__pb2.DiffRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.PctChange = channel.unary_unary(
                '/polarway.v1.DataFrameService/PctChange',
                request_serializer=polarway__pb2.PctChangeRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.AsofJoin = channel.unary_unary(
                '/polarway.v1.DataFrameService/AsofJoin',
                request_serializer=polarway__pb2.AsofJoinRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.FillNull = channel.unary_unary(
                '/polarway.v1.DataFrameService/FillNull',
                request_serializer=polarway__pb2.FillNullRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.FillNan = channel.unary_unary(
                '/polarway.v1.DataFrameService/FillNan',
                request_serializer=polarway__pb2.FillNanRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Interpolate = channel.unary_unary(
                '/polarway.v1.DataFrameService/Interpolate',
                request_serializer=polarway__pb2.InterpolateRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Collect = channel.unary_stream(
                '/polarway.v1.DataFrameService/Collect',
                request_serializer=polarway__pb2.CollectRequest.SerializeToString,
                response_deserializer=polarway__pb2.ArrowBatch.FromString,
                _registered_method=True)
        self.CollectStreaming = channel.unary_stream(
                '/polarway.v1.DataFrameService/CollectStreaming',
                request_serializer=polarway__pb2.CollectStreamingRequest.SerializeToString,
                response_deserializer=polarway__pb2.ArrowBatch.FromString,
                _registered_method=True)
        self.Explain = channel.unary_unary(
                '/polarway.v1.DataFrameService/Explain',
                request_serializer=polarway__pb2.ExplainRequest.SerializeToString,
                response_deserializer=polarway__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/polarway.v1.DataFrameService/GetSchema',
                request_serializer=polarway__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=polarway__pb2.SchemaResponse.FromString,
                _registered_method=True)
        self.GetShape = channel.unary_unary(
                '/polarway.v1.DataFrameService/GetShape',
                request_serializer=polarway__pb2.GetShapeRequest.SerializeToString,
                response_deserializer=polarway__pb2.ShapeResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/polarway.v1.DataFrameService/GetStats',
                request_serializer=polarway__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=polarway__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Describe = channel.unary_unary(
                '/polarway.v1.DataFrameService/Describe',
                request_serializer=polarway__pb2.DescribeRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.CreateFromArrow = channel.unary_unary(
                '/polarway.v1.DataFrameService/CreateFromArrow',
                request_serializer=polarway__pb2.CreateFromArrowRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.Clone = channel.unary_unary(
                '/polarway.v1.DataFrameService/Clone',
                request_serializer=polarway__pb2.CloneRequest.SerializeToString,
                response_deserializer=polarway__pb2.DataFrameHandle.FromString,
                _registered_method=True)
        self.DropHandle = channel.unary_unary(
                '/polarway.v1.DataFrameService/DropHandle',
                request_serializer=polarway__pb2.DropHandleRequest.SerializeToString,
                response_deserializer=polarway__pb2.DropHandleResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/polarway.v1.DataFrameService/Heartbeat',
                request_serializer=polarway__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=polarway__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class DataFrameServiceServicer(object):
    """Main DataFrame service - all operations are immutable and return new handles
    ===== File I/O Operations =====
    """

    def ReadParquet(self, request, context):
        """Read from Parquet with optional predicate/projection pushdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCsv(self, request, context):
        """Read from CSV with schema inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRestApi(self, request, context):
        """Read from REST API (simplified version - returns handle directly)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteParquet(self, request, context):
        """Write DataFrame to Parquet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteCsv(self, request, context):
        """Write DataFrame to CSV
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWebSocket(self, request, context):
        """===== Network Data Sources (Streaming) =====

        Connect to WebSocket and stream data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRestApi(self, request, context):
        """Load data from REST API with pagination support
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGrpc(self, request, context):
        """Connect to another gRPC service and stream data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessageQueue(self, request, context):
        """Subscribe to message queue/event stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Filter(self, request, context):
        """===== Core DataFrame Operations =====
        All operations return new DataFrameHandle (immutable)

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Select(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithColumns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unique(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Limit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Head(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Slice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GroupBy(self, request, context):
        """===== Aggregation Operations =====

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Agg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pivot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Melt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Join(self, request, context):
        """===== Join Operations =====

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cross(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsTimeSeries(self, request, context):
        """===== Time-Series Operations =====

        Convert to TimeSeriesFrame
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resample(self, request, context):
        """Resample time-series data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollingWindow(self, request, context):
        """Rolling window operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lag(self, request, context):
        """Lag/Lead operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diff(self, request, context):
        """Difference operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PctChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsofJoin(self, request, context):
        """Time-series join (asof)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FillNull(self, request, context):
        """Fill operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FillNan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interpolate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Collect(self, request, context):
        """===== Execution & Collection =====

        Collect all data (returns Arrow IPC stream)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectStreaming(self, request, context):
        """Collect with streaming execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explain(self, request, context):
        """Lazy execution - returns optimized plan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """===== Metadata Operations =====

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFromArrow(self, request, context):
        """===== Handle Management =====

        Create DataFrame from Arrow IPC data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clone(self, request, context):
        """Clone a handle (cheap - shares underlying data)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropHandle(self, request, context):
        """Drop handle and free resources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Keep handle alive (extend TTL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataFrameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadParquet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadParquet,
                    request_deserializer=polarway__pb2.ReadParquetRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'ReadCsv': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCsv,
                    request_deserializer=polarway__pb2.ReadCsvRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'ReadRestApi': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRestApi,
                    request_deserializer=polarway__pb2.RestApiRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'WriteParquet': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteParquet,
                    request_deserializer=polarway__pb2.WriteParquetRequest.FromString,
                    response_serializer=polarway__pb2.WriteResponse.SerializeToString,
            ),
            'WriteCsv': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteCsv,
                    request_deserializer=polarway__pb2.WriteCsvRequest.FromString,
                    response_serializer=polarway__pb2.WriteResponse.SerializeToString,
            ),
            'StreamWebSocket': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWebSocket,
                    request_deserializer=polarway__pb2.WebSocketSourceRequest.FromString,
                    response_serializer=polarway__pb2.ArrowBatch.SerializeToString,
            ),
            'StreamRestApi': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRestApi,
                    request_deserializer=polarway__pb2.RestApiRequest.FromString,
                    response_serializer=polarway__pb2.ArrowBatch.SerializeToString,
            ),
            'StreamGrpc': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGrpc,
                    request_deserializer=polarway__pb2.GrpcStreamRequest.FromString,
                    response_serializer=polarway__pb2.ArrowBatch.SerializeToString,
            ),
            'StreamMessageQueue': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessageQueue,
                    request_deserializer=polarway__pb2.MessageQueueRequest.FromString,
                    response_serializer=polarway__pb2.ArrowBatch.SerializeToString,
            ),
            'Filter': grpc.unary_unary_rpc_method_handler(
                    servicer.Filter,
                    request_deserializer=polarway__pb2.FilterRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=polarway__pb2.SelectRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'WithColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.WithColumn,
                    request_deserializer=polarway__pb2.WithColumnRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'WithColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.WithColumns,
                    request_deserializer=polarway__pb2.WithColumnsRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Drop': grpc.unary_unary_rpc_method_handler(
                    servicer.Drop,
                    request_deserializer=polarway__pb2.DropRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=polarway__pb2.RenameRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Sort': grpc.unary_unary_rpc_method_handler(
                    servicer.Sort,
                    request_deserializer=polarway__pb2.SortRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Unique': grpc.unary_unary_rpc_method_handler(
                    servicer.Unique,
                    request_deserializer=polarway__pb2.UniqueRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Limit': grpc.unary_unary_rpc_method_handler(
                    servicer.Limit,
                    request_deserializer=polarway__pb2.LimitRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Head': grpc.unary_unary_rpc_method_handler(
                    servicer.Head,
                    request_deserializer=polarway__pb2.HeadRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Tail': grpc.unary_unary_rpc_method_handler(
                    servicer.Tail,
                    request_deserializer=polarway__pb2.TailRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Slice': grpc.unary_unary_rpc_method_handler(
                    servicer.Slice,
                    request_deserializer=polarway__pb2.SliceRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'GroupBy': grpc.unary_unary_rpc_method_handler(
                    servicer.GroupBy,
                    request_deserializer=polarway__pb2.GroupByRequest.FromString,
                    response_serializer=polarway__pb2.GroupByHandle.SerializeToString,
            ),
            'Agg': grpc.unary_unary_rpc_method_handler(
                    servicer.Agg,
                    request_deserializer=polarway__pb2.AggRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Pivot': grpc.unary_unary_rpc_method_handler(
                    servicer.Pivot,
                    request_deserializer=polarway__pb2.PivotRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Melt': grpc.unary_unary_rpc_method_handler(
                    servicer.Melt,
                    request_deserializer=polarway__pb2.MeltRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=polarway__pb2.JoinRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Cross': grpc.unary_unary_rpc_method_handler(
                    servicer.Cross,
                    request_deserializer=polarway__pb2.CrossRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'AsTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.AsTimeSeries,
                    request_deserializer=polarway__pb2.AsTimeSeriesRequest.FromString,
                    response_serializer=polarway__pb2.TimeSeriesHandle.SerializeToString,
            ),
            'Resample': grpc.unary_unary_rpc_method_handler(
                    servicer.Resample,
                    request_deserializer=polarway__pb2.ResampleRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'RollingWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.RollingWindow,
                    request_deserializer=polarway__pb2.RollingWindowRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Lag': grpc.unary_unary_rpc_method_handler(
                    servicer.Lag,
                    request_deserializer=polarway__pb2.LagRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Lead': grpc.unary_unary_rpc_method_handler(
                    servicer.Lead,
                    request_deserializer=polarway__pb2.LeadRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Diff': grpc.unary_unary_rpc_method_handler(
                    servicer.Diff,
                    request_deserializer=polarway__pb2.DiffRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'PctChange': grpc.unary_unary_rpc_method_handler(
                    servicer.PctChange,
                    request_deserializer=polarway__pb2.PctChangeRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'AsofJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.AsofJoin,
                    request_deserializer=polarway__pb2.AsofJoinRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'FillNull': grpc.unary_unary_rpc_method_handler(
                    servicer.FillNull,
                    request_deserializer=polarway__pb2.FillNullRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'FillNan': grpc.unary_unary_rpc_method_handler(
                    servicer.FillNan,
                    request_deserializer=polarway__pb2.FillNanRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Interpolate': grpc.unary_unary_rpc_method_handler(
                    servicer.Interpolate,
                    request_deserializer=polarway__pb2.InterpolateRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Collect': grpc.unary_stream_rpc_method_handler(
                    servicer.Collect,
                    request_deserializer=polarway__pb2.CollectRequest.FromString,
                    response_serializer=polarway__pb2.ArrowBatch.SerializeToString,
            ),
            'CollectStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.CollectStreaming,
                    request_deserializer=polarway__pb2.CollectStreamingRequest.FromString,
                    response_serializer=polarway__pb2.ArrowBatch.SerializeToString,
            ),
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=polarway__pb2.ExplainRequest.FromString,
                    response_serializer=polarway__pb2.ExplainResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=polarway__pb2.GetSchemaRequest.FromString,
                    response_serializer=polarway__pb2.SchemaResponse.SerializeToString,
            ),
            'GetShape': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShape,
                    request_deserializer=polarway__pb2.GetShapeRequest.FromString,
                    response_serializer=polarway__pb2.ShapeResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=polarway__pb2.GetStatsRequest.FromString,
                    response_serializer=polarway__pb2.StatsResponse.SerializeToString,
            ),
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=polarway__pb2.DescribeRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'CreateFromArrow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFromArrow,
                    request_deserializer=polarway__pb2.CreateFromArrowRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'Clone': grpc.unary_unary_rpc_method_handler(
                    servicer.Clone,
                    request_deserializer=polarway__pb2.CloneRequest.FromString,
                    response_serializer=polarway__pb2.DataFrameHandle.SerializeToString,
            ),
            'DropHandle': grpc.unary_unary_rpc_method_handler(
                    servicer.DropHandle,
                    request_deserializer=polarway__pb2.DropHandleRequest.FromString,
                    response_serializer=polarway__pb2.DropHandleResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=polarway__pb2.HeartbeatRequest.FromString,
                    response_serializer=polarway__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polarway.v1.DataFrameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polarway.v1.DataFrameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataFrameService(object):
    """Main DataFrame service - all operations are immutable and return new handles
    ===== File I/O Operations =====
    """

    @staticmethod
    def ReadParquet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/ReadParquet',
            polarway__pb2.ReadParquetRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadCsv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/ReadCsv',
            polarway__pb2.ReadCsvRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRestApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/ReadRestApi',
            polarway__pb2.RestApiRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteParquet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/WriteParquet',
            polarway__pb2.WriteParquetRequest.SerializeToString,
            polarway__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteCsv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/WriteCsv',
            polarway__pb2.WriteCsvRequest.SerializeToString,
            polarway__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWebSocket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polarway.v1.DataFrameService/StreamWebSocket',
            polarway__pb2.WebSocketSourceRequest.SerializeToString,
            polarway__pb2.ArrowBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRestApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polarway.v1.DataFrameService/StreamRestApi',
            polarway__pb2.RestApiRequest.SerializeToString,
            polarway__pb2.ArrowBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGrpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polarway.v1.DataFrameService/StreamGrpc',
            polarway__pb2.GrpcStreamRequest.SerializeToString,
            polarway__pb2.ArrowBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessageQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polarway.v1.DataFrameService/StreamMessageQueue',
            polarway__pb2.MessageQueueRequest.SerializeToString,
            polarway__pb2.ArrowBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Filter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Filter',
            polarway__pb2.FilterRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Select',
            polarway__pb2.SelectRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/WithColumn',
            polarway__pb2.WithColumnRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/WithColumns',
            polarway__pb2.WithColumnsRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Drop',
            polarway__pb2.DropRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Rename',
            polarway__pb2.RenameRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Sort',
            polarway__pb2.SortRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unique(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Unique',
            polarway__pb2.UniqueRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Limit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Limit',
            polarway__pb2.LimitRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Head(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Head',
            polarway__pb2.HeadRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Tail',
            polarway__pb2.TailRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Slice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Slice',
            polarway__pb2.SliceRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GroupBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/GroupBy',
            polarway__pb2.GroupByRequest.SerializeToString,
            polarway__pb2.GroupByHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Agg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Agg',
            polarway__pb2.AggRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pivot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Pivot',
            polarway__pb2.PivotRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Melt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Melt',
            polarway__pb2.MeltRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Join',
            polarway__pb2.JoinRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cross(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Cross',
            polarway__pb2.CrossRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/AsTimeSeries',
            polarway__pb2.AsTimeSeriesRequest.SerializeToString,
            polarway__pb2.TimeSeriesHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Resample',
            polarway__pb2.ResampleRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollingWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/RollingWindow',
            polarway__pb2.RollingWindowRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Lag',
            polarway__pb2.LagRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Lead',
            polarway__pb2.LeadRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Diff',
            polarway__pb2.DiffRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PctChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/PctChange',
            polarway__pb2.PctChangeRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsofJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/AsofJoin',
            polarway__pb2.AsofJoinRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FillNull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/FillNull',
            polarway__pb2.FillNullRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FillNan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/FillNan',
            polarway__pb2.FillNanRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interpolate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Interpolate',
            polarway__pb2.InterpolateRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Collect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polarway.v1.DataFrameService/Collect',
            polarway__pb2.CollectRequest.SerializeToString,
            polarway__pb2.ArrowBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polarway.v1.DataFrameService/CollectStreaming',
            polarway__pb2.CollectStreamingRequest.SerializeToString,
            polarway__pb2.ArrowBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Explain',
            polarway__pb2.ExplainRequest.SerializeToString,
            polarway__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/GetSchema',
            polarway__pb2.GetSchemaRequest.SerializeToString,
            polarway__pb2.SchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/GetShape',
            polarway__pb2.GetShapeRequest.SerializeToString,
            polarway__pb2.ShapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/GetStats',
            polarway__pb2.GetStatsRequest.SerializeToString,
            polarway__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Describe',
            polarway__pb2.DescribeRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFromArrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/CreateFromArrow',
            polarway__pb2.CreateFromArrowRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Clone',
            polarway__pb2.CloneRequest.SerializeToString,
            polarway__pb2.DataFrameHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropHandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/DropHandle',
            polarway__pb2.DropHandleRequest.SerializeToString,
            polarway__pb2.DropHandleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polarway.v1.DataFrameService/Heartbeat',
            polarway__pb2.HeartbeatRequest.SerializeToString,
            polarway__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
